######################################################################
# Automatically generated by qmake (3.1) Wed May 10 21:42:00 2017
######################################################################

TEMPLATE = app
TARGET = lab10_11
INCLUDEPATH += .
QT += core gui
QT += widgets

# Input
SOURCES += main.cpp
