######################################################################
# Automatically generated by qmake (3.1) Thu May 18 14:15:24 2017
######################################################################

TEMPLATE = app
TARGET = lab10
INCLUDEPATH += .
QT += core gui widgets

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
